### PR TITLE
fix: support multiple redirect URIs with wildcard path matching

### LINKED ISSUE #440: OAuth2 client redirect_uri: support multiple URIs and wildcard path matching
## Problem

The `Client.RedirectURI` field is a single string and `Allow()` uses `reflect.DeepEqual` on parsed URLs to validate redirect URIs. This has two limitations:

1. **Only one redirect URI per client** — RFC 6749 §3.1.2 allows registering multiple redirect URIs
2. **No wildcard/prefix matching** — testing tools like the OpenID Foundation conformance suite generate dynamic callback URLs (e.g. `/test/a/<random-alias>/callback`), requiring prefix-based matching

## Fix

- Replace `RedirectURI string` with `RedirectURIs RedirectURIs` (custom type)
- `RedirectURIs` unmarshals from either a single YAML/JSON string or an array
- `Contains()` method supports exact matching and `/*` suffix wildcard (scheme+host exact match, path prefix match)
- `Allow()` updated to use `Contains()` instead of `reflect.DeepEqual`

## Security considerations

- Wildcard matching validates scheme and host exactly; only path prefix is flexible
- `/*` suffix is an explicit opt-in pattern — no implicit wildcarding

Found during OID4VCI conformance testing.

### PR DESCRIPTION
**Pull request by leifj**
Replace `Client.RedirectURI` (single string) with `Client.RedirectURIs` (custom type that accepts single string or array in YAML/JSON).

## Changes

- **`RedirectURIs` type**: flexible unmarshalling (single string or array) for both YAML and JSON
- **`Contains()` method**: exact matching + `/*` suffix wildcard (enforces scheme+host equality, only path prefix is flexible)
- **`Allow()`**: uses `Contains()` instead of `reflect.DeepEqual`
- **`endpoints_users.go`**: updated to use `client.RedirectURIs[0]` instead of `client.RedirectURI`
- **Tests**: 7 test cases for `TestRedirectURIsContains` covering exact, wildcard, wrong host/scheme, multiple URIs

## Motivation

The conformance suite uses dynamic redirect URIs with path suffixes. The old single-string `RedirectURI` with exact equality can't match these. Wildcard support allows configuring `https://host/*` in config.

Fixes #440

### CODE REVIEW

File: pkg/oauth2/client_assertion.go [hunk 1]
```diff
@@ -9,9 +9,18 @@ import (
...
+// NOTE: This does NOT implement full private_key_jwt authentication. The extracted
+// client_id is only used for client lookup; actual client authentication relies on
+// pre-registered client configurations and DPoP binding. Full JWT assertion
+// verification (signature, aud, exp, jti) should be added when proper private_key_jwt
+// support is implemented.
+//
+// SECURITY: Because the JWT is not signature-verified, the caller MUST validate
+// the extracted client_id against a trusted client registry before granting access.
+// The handler enforces this via Clients.Get() lookup immediately after extraction.
 func ExtractClientIDFromAssertion(assertion string) (string, error) {
```
[the remark this answers is not in the document]
Comment (leifj) [reply pkg/oauth2/client_assertion.go:22]: This file was introduced in PR #453 (now merged to main) and is used by `handlers_oauth.go` in the token endpoint. It appears in this PR's diff because of the merge commit bringing upstream/main into this branch — the only delta from upstream is the expanded doc comment. No action needed.

File: pkg/oauth2/clients.go [hunk 2]
```diff
@@ -139,6 +139,9 @@ func (c *Clients) Allow(clientID, redirectURI, scope string) (*Client, error) {
 		return nil, errors.New("client not found in config")
 	}
 
+	if len(client.RedirectURIs) == 0 {
+		return nil, errors.New("no redirect_uri configured for client")
+	}
```
[the remark this answers is not in the document]
Comment (leifj) [reply pkg/oauth2/clients.go:144]: Added a TestAllow case ("client with no redirect URIs configured") exercising the empty RedirectURIs branch and its "no redirect_uri configured for client" error.

File: pkg/oauth2/clients_test.go [hunk 3]
```diff
@@ -135,6 +135,12 @@ func TestRedirectURIsContains(t *testing.T) {
 			check:    "http://example.com/test/a/some-alias/callback",
 			expected: false,
 		},
+		{
+			name:     "wildcard path traversal via dot-segments",
+			uris:     RedirectURIs{"https://example.com/test/a/*"},
+			check:    "https://example.com/test/a/../evil",
+			expected: false,
+		},
```
[the remark this answers is not in the document]
Comment (leifj) [reply pkg/oauth2/clients_test.go:165]: De-duplicated: this case now uses percent-encoded dot-segments (https://example.com/test/a/%2e%2e/evil) to cover an additional traversal variant, distinct from the literal ../ case.

File: pkg/oauth2/clients.go [hunk 4]
```diff
@@ -139,6 +139,9 @@ func (c *Clients) Allow(clientID, redirectURI, scope string) (*Client, error) {
 		return nil, errors.New("client not found in config")
 	}
 
+	if len(client.RedirectURIs) == 0 {
+		return nil, errors.New("no redirect_uri configured for client")
```
[the remark this answers is not in the document]
Comment (leifj) [reply pkg/oauth2/clients.go:143]: Fixed in 2b6cb717. Added a nil guard so a config decoding to a nil *Client (e.g. `client_id: null`) now returns "client not found in config" instead of panicking. Applied to both Allow and Get, with a new TestAllow case ("nil client value in config") covering it.
